package cli

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/taehyun/lg/internal/config"
	"github.com/taehyun/lg/internal/fuse"
	"github.com/taehyun/lg/internal/shell"
)

func newShellCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "shell",
		Short: "Start the unified shell (mounts the FUSE tree, runs your $SHELL)",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runShell()
		},
	}
}

func runShell() error {
	c, err := loadGhost()
	if err != nil {
		return err
	}
	matcher, err := buildMatcher(c)
	if err != nil {
		return err
	}
	store, journal, err := openGhostStores()
	if err != nil {
		return err
	}
	defer store.Close()
	defer journal.Close()

	// Long-lived connection + FUSE mount for this shell session.
	client := newClient(c)
	defer client.Close()
	source := fuse.NewClientSource(client)
	backend := fuse.NewBackend(c, store, journal, source, matcher)
	client.OnInvalidate(backend.Invalidate)

	mount, err := fuse.NewMount(c.LocalRoot, backend)
	if err != nil {
		return fmt.Errorf("mount failed: %w", err)
	}
	defer mount.Unmount()

	if _, _, err := shell.InstallIntegration(); err != nil {
		return err
	}
	tabID, err := genTabID()
	if err != nil {
		return err
	}
	defer shell.ClearState(tabID)

	fmt.Fprintf(os.Stderr, "lg: mounted %s, entering shell (tab %s)\n", c.LocalRoot, tabID)
	return execUserShell(c, tabID)
}

// execUserShell runs the user's real shell with lg integration injected via
// ZDOTDIR (zsh) or an rcfile (bash), preserving their normal config (D2).
func execUserShell(c *config.Config, tabID string) error {
	shellPath := os.Getenv("SHELL")
	if shellPath == "" {
		shellPath = "/bin/zsh"
	}
	env := append(os.Environ(),
		"LG_TAB_ID="+tabID,
		"LG_PROJECT="+projectID(c),
	)

	var cmd *exec.Cmd
	base := filepath.Base(shellPath)
	switch {
	case strings.Contains(base, "zsh"):
		zdot, err := writeZdotdir()
		if err != nil {
			return err
		}
		env = append(env, "ZDOTDIR="+zdot)
		cmd = exec.Command(shellPath, "-i")
	case strings.Contains(base, "bash"):
		rc := filepath.Join(config.Dir(), "hooks", "bash-integration.bash")
		cmd = exec.Command(shellPath, "--rcfile", rc, "-i")
	default:
		cmd = exec.Command(shellPath, "-i")
	}
	cmd.Env = env
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	return cmd.Run()
}

// writeZdotdir creates a ZDOTDIR whose .zshrc sources the user's real config
// then the lg integration, so nothing the user has is lost (D2).
func writeZdotdir() (string, error) {
	dir := filepath.Join(config.Dir(), "run", "zdotdir")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	home, _ := os.UserHomeDir()
	integ := filepath.Join(config.Dir(), "hooks", "zsh-integration.zsh")
	content := fmt.Sprintf(`# auto-generated by lg
export LG_BASE_PS1=""
[ -f %q ] && source %q
[ -f %q ] && source %q
source %q
`,
		filepath.Join(home, ".zshrc"), filepath.Join(home, ".zshrc"),
		filepath.Join(home, ".zprofile"), filepath.Join(home, ".zprofile"),
		integ)
	if err := os.WriteFile(filepath.Join(dir, ".zshrc"), []byte(content), 0o644); err != nil {
		return "", err
	}
	return dir, nil
}

func projectID(c *config.Config) string {
	return filepath.Base(strings.TrimRight(c.LocalRoot, "/"))
}

func genTabID() (string, error) {
	b := make([]byte, 6)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
