# Homebrew formula for Live Git (lg). Regenerated by scripts/publish-release.sh —
# do not hand-edit; bump the release instead.
#
#   brew tap iamtaehyunpark/livegit
#   brew install lg
#
# Homebrew downloads the prebuilt binary — users never need Go.
class Lg < Formula
  desc "Live Git — run commands on a remote server and browse its tree locally"
  homepage "https://github.com/iamtaehyunpark/livegit"
  version "1.4.5"

  on_macos do
    on_arm do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.4.5/lg-darwin-arm64"
      sha256 "fb370a59fa9883133229cc3c3f4d89d68f35df9602b91ce1199c54e6164874f0"
    end
    on_intel do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.4.5/lg-darwin-amd64"
      sha256 "2d9f1f5c7c594885e63028fc23c3f40ba6977e221f5e65d88b27b4a2d9507fc7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.4.5/lg-linux-arm64"
      sha256 "2c38ea19f991c2da0f89ae163d1d718bcdcfbbabb7d659c3b57051919a4b9fb5"
    end
    on_intel do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.4.5/lg-linux-amd64"
      sha256 "79a1da38f6b31baa744d49891b8f674bc6a1ca85cc761f247f29e9d3e45ed191"
    end
  end

  def install
    bin.install Dir["*"].first => "lg"
  end

  test do
    assert_match "lg", shell_output("#{bin}/lg --version")
  end
end
