# Homebrew formula for Live Git (lg). Regenerated by scripts/publish-release.sh —
# do not hand-edit; bump the release instead.
#
#   brew tap iamtaehyunpark/livegit
#   brew install lg
#
# Homebrew downloads the prebuilt binary — users never need Go.
class Lg < Formula
  desc "Live Git — run commands on a remote server and browse its tree locally"
  homepage "https://github.com/iamtaehyunpark/livegit"
  version "1.3.5"

  on_macos do
    on_arm do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.3.5/lg-darwin-arm64"
      sha256 "799b4d3bfba55fe47b8410b541ea6fc6a0596a3ca6cb58f601b0d85a5ca8dd06"
    end
    on_intel do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.3.5/lg-darwin-amd64"
      sha256 "978cd84986cb167b4ff1c9984c4ad8cf3bc7417000615875df614e3a9ed383ce"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.3.5/lg-linux-arm64"
      sha256 "29a5ae655a1c2d219440e78d6acbc634427da75ff4afae790c227724d7391c8b"
    end
    on_intel do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.3.5/lg-linux-amd64"
      sha256 "a8996593ac91b382693232fe8ee3633f4ac37ff6549f4bfd52958c0dbd0f6b66"
    end
  end

  def install
    bin.install Dir["*"].first => "lg"
  end

  test do
    assert_match "lg", shell_output("#{bin}/lg --version")
  end
end
