# Homebrew formula for Live Git (lg). Regenerated by scripts/publish-release.sh —
# do not hand-edit; bump the release instead.
#
#   brew tap iamtaehyunpark/livegit
#   brew install lg
#
# Homebrew downloads the prebuilt binary — users never need Go.
class Lg < Formula
  desc "Live Git — run commands on a remote server and browse its tree locally"
  homepage "https://github.com/iamtaehyunpark/livegit"
  version "1.2.0"

  on_macos do
    on_arm do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.2.0/lg-darwin-arm64"
      sha256 "bae0cde7c08d027038fd553838372e980479dbb6c23524a5fd04b78533b78f22"
    end
    on_intel do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.2.0/lg-darwin-amd64"
      sha256 "1a9ad89c20ff1e27c17e91ca30c3c714429e9378d1f4ff8db21293240240418b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.2.0/lg-linux-arm64"
      sha256 "26fa53860a3d7cc7246e5315d04b39a128f70d3969b870c13fc184cff48b9417"
    end
    on_intel do
      url "https://github.com/iamtaehyunpark/livegit/releases/download/v1.2.0/lg-linux-amd64"
      sha256 "cc879d511e35e1bbf2555431e264b4736ee2b1f67c3e93973f4c6dec73a8df82"
    end
  end

  def install
    bin.install Dir["*"].first => "lg"
  end

  test do
    assert_match "lg", shell_output("#{bin}/lg --version")
  end
end
