#!/usr/bin/env sh
# Cut and publish an lg release in one step.
#
#   scripts/publish-release.sh vX.Y.Z
#   (or: make publish TAG=vX.Y.Z)
#
# It does everything needed for both install paths (curl installer + Homebrew):
#   1. preflight — clean tree, gh authed, valid version, tag not already used
#   2. tag the release and push the tag
#   3. `make release` — static binaries for every platform, stamped with the tag
#   4. hash each binary (sha256)
#   5. regenerate Formula/lg.rb from those hashes (in THIS repo)
#   6. create the GitHub release and upload the binaries
#   7. commit the refreshed formula here, and push a copy to the Homebrew tap repo
#
# Requires: git, go, gh (authenticated), and shasum or sha256sum.
set -eu

REPO="iamtaehyunpark/livegit"
TAP_REPO="iamtaehyunpark/homebrew-livegit"
# Platform binaries produced by `make release` (dist/lg-<plat>), in formula order.
PLATFORMS="darwin-arm64 darwin-amd64 linux-arm64 linux-amd64"

die() { echo "publish: $*" >&2; exit 1; }

# --- 1. preflight ---------------------------------------------------------
TAG="${1:-}"
[ -n "$TAG" ] || die "usage: scripts/publish-release.sh vX.Y.Z"
echo "$TAG" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' || die "version must look like v1.2.3 (got '$TAG')"
VERSION="${TAG#v}" # formula wants the bare number

command -v gh >/dev/null || die "gh (GitHub CLI) not found"
gh auth status >/dev/null 2>&1 || die "gh is not authenticated (run: gh auth login)"

cd "$(git rev-parse --show-toplevel)"
[ -z "$(git status --porcelain)" ] || die "working tree is dirty — commit or stash first"
git rev-parse "$TAG" >/dev/null 2>&1 && die "tag $TAG already exists"

sha256() { # portable: prefer shasum, fall back to sha256sum
  if command -v shasum >/dev/null; then shasum -a 256 "$1" | awk '{print $1}';
  else sha256sum "$1" | awk '{print $1}'; fi
}

echo "==> Publishing $TAG"

# --- 2. tag + push --------------------------------------------------------
git tag -a "$TAG" -m "lg $TAG"
git push origin "$TAG"

# --- 3. build release binaries (stamped with the tag via git describe) -----
make release

# --- 4. hash each binary --------------------------------------------------
for p in $PLATFORMS; do
  f="dist/lg-$p"
  [ -f "$f" ] || die "expected $f from 'make release'"
  eval "SHA_$(echo "$p" | tr '-' '_')=$(sha256 "$f")"
done

# --- 5. regenerate Formula/lg.rb ------------------------------------------
base="https://github.com/$REPO/releases/download/$TAG"
cat > Formula/lg.rb <<EOF
# Homebrew formula for Live Git (lg). Regenerated by scripts/publish-release.sh —
# do not hand-edit; bump the release instead.
#
#   brew tap iamtaehyunpark/livegit
#   brew install lg
#
# Homebrew downloads the prebuilt binary — users never need Go.
class Lg < Formula
  desc "Live Git — run commands on a remote server and browse its tree locally"
  homepage "https://github.com/$REPO"
  version "$VERSION"

  on_macos do
    on_arm do
      url "$base/lg-darwin-arm64"
      sha256 "$SHA_darwin_arm64"
    end
    on_intel do
      url "$base/lg-darwin-amd64"
      sha256 "$SHA_darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$base/lg-linux-arm64"
      sha256 "$SHA_linux_arm64"
    end
    on_intel do
      url "$base/lg-linux-amd64"
      sha256 "$SHA_linux_amd64"
    end
  end

  def install
    bin.install Dir["*"].first => "lg"
  end

  test do
    assert_match "lg", shell_output("#{bin}/lg --version")
  end
end
EOF
echo "==> Regenerated Formula/lg.rb for $VERSION"

# --- 6. create the GitHub release + upload binaries -----------------------
gh release create "$TAG" \
  dist/lg-darwin-arm64 dist/lg-darwin-amd64 dist/lg-linux-amd64 dist/lg-linux-arm64 \
  --repo "$REPO" --title "lg $TAG" \
  --notes "Live Git $TAG — run any command on your remote server inline, and browse its whole tree locally.

**Install (prebuilt, no Go needed):**
\`\`\`sh
curl -fsSL https://raw.githubusercontent.com/$REPO/main/install.sh | sh
\`\`\`
or \`brew tap iamtaehyunpark/livegit && brew install lg\`.

Static binaries for macOS and Linux (arm64/amd64) are attached."

# --- 7. commit the formula here + push it to the tap repo ------------------
git add Formula/lg.rb
git commit -m "Formula: release $TAG"
git push origin HEAD

tap_dir="$(mktemp -d)"
git clone --depth 1 "https://github.com/$TAP_REPO.git" "$tap_dir"
mkdir -p "$tap_dir/Formula"
cp Formula/lg.rb "$tap_dir/Formula/lg.rb"
git -C "$tap_dir" add Formula/lg.rb
if git -C "$tap_dir" diff --cached --quiet; then
  echo "==> Tap already up to date"
else
  git -C "$tap_dir" commit -m "lg $TAG"
  git -C "$tap_dir" push origin HEAD
fi
rm -rf "$tap_dir"

echo "==> Done. Published $TAG to $REPO and $TAP_REPO"
echo "    brew update && brew upgrade lg   # for existing users"
