package transport

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/iamtaehyunpark/livegit/internal/config"
)

// SSH_ASKPASS support: on a password+Duo host, `lg connect` opens the master
// with SSH_ASKPASS_REQUIRE=force so ssh routes EVERY prompt to our helper
// instead of the tty. The helper (`lg askpass`, hidden) answers password
// prompts from the encrypted store and relays anything else — the Duo menu, a
// passcode, a host-key confirmation — to the real terminal via /dev/tty. Net
// effect: the user never types the password again; they only answer Duo.
//
// SSH_ASKPASS accepts a single program path with NO arguments, so we drop a
// two-line shim script under <project>/.lg/run/ that re-invokes this binary's
// `askpass` subcommand with the project pinned via LG_HOME (ssh runs the
// helper with an arbitrary cwd, so `.lg/` discovery can't be relied on).
// SSH_ASKPASS_REQUIRE=force needs OpenSSH >= 8.4 (macOS has shipped newer for
// years); on an older ssh the variables are ignored and the password prompt
// simply renders on the tty as before.

// askpassEnv writes the shim script and returns the env additions for the
// `ssh` invocation. The script holds no secrets — the password stays encrypted
// in .lg/credentials and is decrypted by `lg askpass` at prompt time.
func askpassEnv() ([]string, error) {
	self, err := os.Executable()
	if err != nil {
		return nil, err
	}
	dir := config.Dir()
	runDir := filepath.Join(dir, "run")
	if err := os.MkdirAll(runDir, 0o755); err != nil {
		return nil, err
	}
	script := filepath.Join(runDir, "askpass.sh")
	body := "#!/bin/sh\n" +
		"# generated by lg — SSH_ASKPASS shim (no secrets here; the password stays\n" +
		"# encrypted in .lg/credentials and is decrypted by `lg askpass` on demand).\n" +
		fmt.Sprintf("LG_HOME=%s exec %s askpass \"$@\"\n", shQuote(dir), shQuote(self))
	if err := os.WriteFile(script, []byte(body), 0o755); err != nil {
		return nil, err
	}
	return []string{"SSH_ASKPASS=" + script, "SSH_ASKPASS_REQUIRE=force"}, nil
}

// shQuote single-quotes s for /bin/sh (the paths land inside the shim script).
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
